- name: Deploy UnderCloud and OverCloud
  hosts: all
  roles:
    - launch-nodes node_type=undercloud
    - prepare-undercloud
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

