- name: Creating stack user
  command: sleep 10

- name: Configuring sudo for stack user
  command: sleep 10

- name: Creating required directories
  command: sleep 10

- name: Configuring hostname
  command: sleep 10

- name: Configuring required repos
  command: sleep 10

- name: Cheking Undercloud Repo settings
  debug: msg="Status=OK. {{item }} "
  with_items:
    - "Core repositories"
    - "Ceph repositories"

- name: Updating package
  command: sleep 10

- name: Rebooting node
  command: sleep 10

